### ISSUE TITLE
Refactor Architecture Docs

### ISSUE THREAD

**Issue by lucksus** [holochain/org#2]
As a Holochain core dev I want to find HC architecture descriptions and decisions so I can easily understand the code and know how to build new modules of HC core.

**Comment by lucksus** [comment]
We might want to write ADRs for:
- [ ] Language: Rust
- [ ] Redux
- [ ] One WASM Ribosome for now (with two supported languages)
- [ ] Alpha1 last major Go release
- [ ] Splitting agent into front-house / back-house - OR NOT
- [ ] Abstraction for network layer
- [ ] Mobile first
- [ ] Support only 64bit archs
- [ ] Writing our own Kademlia implementation
- [ ] Writing HCadmin / container / launcher in C++/Qt
- [ ] DBs for Rust

**Comment by ddd-mtl** [comment]
ADRs will be in the holochain-rust repo under doc/architecture

**Comment by philipbeadle** [comment]
I have used this in the past successfully https://github.com/npryce/adr-tools
