### ISSUE TITLE
check all benchmarking apps and add tickets if needed

### ISSUE THREAD

**Issue by zippy** [holochain/org#28]
child of #1

**Comment by ddd-mtl** [comment]
Sorting:
 - test: OK
- scenario: OK

ApprovedList: DNA error beccause of baseOn property in DNA. After removing it:
 - test: OK
- scenario: OK

Clutter: DNA error beccause of baseOn property in DNA. After removing it:
 - test: FAIL (expecting null, outputting data)
 - scenario: FAIL

DAO:
 -test: OK
- scenario: FAIL (ValidationErrors)

**Comment by ddd-mtl** [comment]
Fixed clutter. getPost was not checking of EntryType of Entry returned by get()

**Comment by ddd-mtl** [comment]
DAO works after changing wait from 3sec to 6sec ...
