### ISSUE TITLE
fix go-proto bugs

### ISSUE THREAD

**Issue by zippy** [holochain/org#37]
As a user I need core to not panic

This ticket just acts as a reference to things in the legacy holochain-proto board.

- [x] panic in `hcdev test` when doing query
- [ ] bridging works

**Comment by zippy** [comment]
on bug fixed in: https://github.com/holochain/holochain-proto/issues/690

**Comment by zippy** [comment]
found the problem in bridging (I think) and have a PR for @philipbeadle on the holochain-proto repo for this bug.  (#718)

**Comment by philipbeadle** [comment]
Works perfectly!!
