### ISSUE TITLE
Update anchors mixin: README (and repo)

### ISSUE THREAD

**Issue by artbrock** [holochain/org#42]
As an app developer I want to be able to easily understand how anchors work, and the theory behind them:

- [x] update readme
- [x] write article for developer.holochain.org

Philip and Art re-implemented anchors with three simple functions:
 - **anchor(anchor):** to find or reference an anchor (note: it creates it if it doesn't exist, and back-populates "parent" anchors so that the whole directory of anchors becomes browsable from a root anchor)
 - **anchors(type):** returns all anchors of a specified type
 - **exists(anchor):** checks to see if specified anchor exists (without creating it)

**Comment by zippy** [comment]
There was an [article on developer.holochain.org](https://developer.holochain.org/Anchors) which I've updated and added to the Articles page.  I think it could use some help.  @philipbeadle, would you be willing to take a look?

**Comment by thedavidmeister** [comment]
@zippy the developer article calls `addAnchor` which i can't find a definition for

**Comment by thedavidmeister** [comment]
also it starts talking about "handles" in the code with no introduction to what that means

**Comment by thedavidmeister** [comment]
this readme is handy though https://github.com/holochain/mixins/tree/master/anchors

**Comment by philipbeadle** [comment]
The article introduces "handles" in the second paragraph "An anchor provides an easy to find, fixed hash, from which you can link to things that are not so easy to find. For example, you can make an anchor for someone's Clutter handle". :) is that not clear enough?

**Comment by thedavidmeister** [comment]
oh it is, weird i missed that somehow >.<

but yeah, `addAnchor` must be some old code, the current `anchor` function is idempotent

**Comment by zippy** [comment]
You know, I actually didn't write that whole piece I think @connorturland
did, I updated some parts of it, and probably missed that.

**Comment by thedavidmeister** [comment]
i think the current MVP code looks more like this with just the one `anchor` fn:

```javascript
function commitAnchoredEntry (entry) {
  return commit(entryLinksName, {
    Links: [{
      Base: anchor(anchorName),
      Link: commit(entryName, entry),
      Tag: entryTagName,
    }]
  });
}

function getEntries() {
  return getLinks(anchor(anchorName), entryTagName);
}
```
