### ISSUE TITLE
Composability & code reuse: next steps

### ISSUE THREAD

**Issue by lucksus** [holochain/org#48]
As a core team member I want to pool our team's intelligence to come up with an overview of possible strategies for composability that will end up in one or more ADRs.

child of #6

**Comment by ddd-mtl** [comment]
#38

**Comment by lucksus** [comment]
We have our first meeting today in one hour. I've prepared this document to log the conversation and for us to share ideas and minutes: https://docs.google.com/document/d/1bNAzp8G74QYieuc6lqYqD0h_-NYLL9zX_SppHQpPmAg/edit?usp=sharing
(@holo.host accounts have edit access)

**Comment by lucksus** [comment]
Recording of our meeting: https://drive.google.com/open?id=1_ikBCPW-4E5JegRDGtFGP5zJFJgFP4uB

**Comment by lucksus** [comment]
Recording of our 2nd meeting: https://drive.google.com/open?id=1E5Q_4CSgJl9tBUGB4qfPAoBr3eBWmMZx

**Comment by lucksus** [comment]
Outcomes:
* more discussion needed for coherence building
* go for attempt to build a nix-based npm-like tool for pulling in zomes into the development directory during development step of an app
* next: writing an ADR to describe inter-app composability

**Comment by thedavidmeister** [comment]
cross linking #47
