### ISSUE TITLE
Dogfooding click dummy

### ISSUE THREAD

**Issue by zippy** [holochain/org#49]
As a team we want a click dummy of a dogfooding app, and in the process  gain skills in design thinking/process

child of #8

- [ ] schedule and run 5 design meetings
- [ ] end up with a super MVP click dummy

**Comment by ddd-mtl** [comment]
Is the dogfooding  app, an app we build with holochain and use ourself internally thats helps with some problem we have and which also serves as a demo app for holochain?

**Comment by ddd-mtl** [comment]
In that regards having an internal is currently an identified need. So dogfooding a fractal/federated wiki app seems useful.

**Comment by zippy** [comment]
Output from 5/30 meeting: https://realtimeboard.com/app/board/o9J_kzDLQzI=/

**Comment by philipbeadle** [comment]
I'm now doing some research on Unity 3D as a way to find abundant presence.

**Comment by philipbeadle** [comment]
Wow, Unity in the browser looks amazing. Massive community, tools are mature, loads of "assets" like Real Terrain, Building tools and game plays.

**Comment by lucksus** [comment]
Meeting recordings:
Day 2: https://drive.google.com/open?id=1TGJiJu0uIpe6kVV5AVULbc76RqlFsLCA
Day 3: https://drive.google.com/open?id=1hOGflBLobPH5cXpxmE07wro7uEGHb9RQ

**Comment by lucksus** [comment]
Click Dummy that was tested with users: https://marvelapp.com/3075ja2

**Comment by lucksus** [comment]
Record of Day 5: https://drive.google.com/open?id=1qhjJfxq0cTHIZsgG8A1RUvUBuqMo4trW
(user testing)

**Comment by lucksus** [comment]
@celestialhanley, can you add your notes from the user testing here?

**Comment by celestialhanley** [comment]
Day 5: Usability testing notes: https://realtimeboard.com/app/board/o9J_kzDLQzI=/

**Comment by bboyatwork** [comment]
Here is a [direct link ](https://marvelapp.com/31d2c27)to the click dummy from design sprint # 2: https://marvelapp.com/31d2c27
