### ISSUE TITLE
DNA packager dev tool

### ISSUE THREAD

**Issue by lucksus** [holochain/org#59]
As a App Dev I want a package manager in the HDK that creates a package from Source Code files.

child of #19

**Comment by lucksus** [comment]
- compiles Rust app code to WASM
- includes WASM code into the package
- does not handle UI yet

**Comment by sphinxc0re** [comment]
@lucksus should this work be happening in the https://github.com/holochain/holochain-cmd repo?

**Comment by sphinxc0re** [comment]
This has only been the first draft. I think we have to talk about this a little more.
