### ISSUE TITLE
Rust library interface

### ISSUE THREAD

**Issue by lucksus** [holochain/org#63]
As the user of the HC lib I need to have a clear interface for it so that I can create HC instances from DNAs and run multiple apps in one container.

This interface should be C compatible so that we can use that from within a Qt app, and thus easily build for mobile platforms.

child of #19

**Comment by ddd-mtl** [comment]
This seems to imply a ADR on being compatible with Qt which has not been written and approved to my knowledge.

**Comment by zippy** [comment]
We did write: https://github.com/holochain/holochain-rust/blob/develop/doc/architecture/decisions/0011-build-hcadmin-app-with-qt-c.md  but you are correct that we haven't approved it.
