### ISSUE TITLE
Basic container app

### ISSUE THREAD

**Issue by lucksus** [holochain/org#64]
As a HC app user I want to have a container app that instantiates the HC rust lib and runs several HC apps, on desktop platforms as well as mobile.

child of #19

- uses rust lib
- localhost webserver

- multiplex multiple web clients to different apps?
- written in C++/Qt?

**Comment by ddd-mtl** [comment]
Or a Rust app that uses Qt? https://github.com/rust-qt/cpp_to_rust

**Comment by zippy** [comment]
@philipbeadle did a first spike here: https://github.com/holochain/holochain-cmd

**Comment by lucksus** [comment]
Qt/QML based system tray icon app: https://github.com/holochain/holosqape

**Comment by lucksus** [comment]
Please review HoloSqape which is in its own repo. linke shared above.
HoloSqape needs these changes to core: https://github.com/holochain/holochain-rust/pull/55
