### ISSUE TITLE
HoloGlobe UX

### ISSUE THREAD

**Issue by lucksus** [holochain/org#67]
We want to do a 2nd UX/UI iteration for the prototype from our design sprint so that we can do another user testing.

child of #8

**Comment by bboyatwork** [comment]
Updates on Design Sprint # 2 for this week
Flow  for the second sprint in is in the Realtime board here: https://realtimeboard.com/app/board/o9J_kzDLQzI=/
User interviews are located [in this folder](https://drive.google.com/drive/u/1/folders/1Z7ukwqw5NxKfmWITCbaQHlfORBCVQM05)
We've duplicated original for v2 and will be updating/completing the click-dummy by end of day Monday 6/25 (nothing's changed yet, but we'll collab here): https://www.icloud.com/keynote/0ijmh5QPb8Mz5V321-CyeDl_A#dogfoodi_prototype_v2
