### ISSUE TITLE
HoloGlobe Click Dummy

### ISSUE THREAD

**Issue by zippy** [holochain/org#69]
As tester of  HoloGlobe I want to be able to click on images to be able to get a sense of the UI of this itteration.

child of #8

**Comment by bboyatwork** [comment]
We've duplicated original for v2 and will be updating/completing the click-dummy by end of day Monday 6/25 (nothing's changed yet, but we'll collab here): https://www.icloud.com/keynote/0ijmh5QPb8Mz5V321-CyeDl_A#dogfoodi_prototype_v2
