### ISSUE TITLE
DNA Spec

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/org#70]
this is a followup/related to #59

this is NOT mechanical, it's about articulating and agreeing on any changes we want to make to the DNA config structure relative to the go implementation

deliverable is a formal beta spec for all the data structures

**Comment by lucksus** [comment]
https://docs.google.com/document/d/1o32_8ePkrB_BtQQz7zCvIrrqanKq0s-623GEH-k_Muo/edit

**Comment by zippy** [comment]
Working spec: https://hackmd.io/rg1X7Fd_QyKeWehMz9a5FQ#
