### ISSUE TITLE
Strategic Decisions

### ISSUE THREAD

**Issue by lucksus** [holochain/org#87]

**Comment by lucksus** [comment]
* Do we need a web UI?
* Can Qt help us with testing?
* App composability in the containter?

**Comment by lucksus** [comment]
I've created a doodle poll for the first days of this sprint: https://doodle.com/poll/yrzeez6bbmqg98k9

**Comment by zippy** [comment]
I think we can close this ticket no? @lucksus

**Comment by lucksus** [comment]
Yes, but I want to add our notes here: https://hackmd.io/lN2pXLa4TNyck9vsn2CqLw?both
We maybe should also create an ADR/decision issue for what we've discussed?
